SportStore/SportStore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Models
{
	public class Cart
	{
		private List<CartLine> cartLineCollection = new List<CartLine>();


		public virtual IEnumerable<CartLine> LinesCollection
		{
			get
			{
				return cartLineCollection;
			}
		}

		public virtual void AddItem(Product product, int quantity)
		{
			CartLine cartLine = cartLineCollection.Where(p => p.Product.ProductID == product.ProductID).FirstOrDefault();

			if (cartLine == null)
			{
				cartLine = new CartLine
				{
					Product = product,
					Quantity = quantity
				};

				cartLineCollection.Add(cartLine);
			}
			else
			{
				cartLine.Quantity += quantity;
			}

		}

		public virtual void RemoveItem(Product product)
		{
			cartLineCollection.RemoveAll(p => p.Product.ProductID == product.ProductID);
		}

		public virtual decimal ComputeTotalValue()
		{
			decimal totalValue = cartLineCollection.Sum(p => p.Quantity * p.Product.Price);

			return totalValue;
		}

		public virtual void ClearCart()
		{
			cartLineCollection.Clear();
		}

	}
}

SportStore/SportStore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportStore.Infrastructure;
using SportStore.Models;

namespace SportStore.Controllers
{
	public class CartController : Controller
	{
		private IProductRepository _repository;
		private Cart _cart;

		public CartController(IProductRepository repository, Cart cart)
		{
			_repository = repository;
			_cart = cart;
		}

		public ActionResult Index(string returnUrl)
		{
			CartIndexViewModel cartIndexViewModel = new CartIndexViewModel
			{
				Cart = _cart,
				ReturnUrl = returnUrl
			};

			return View(cartIndexViewModel);
		}

		public RedirectToActionResult AddToCart(int productID, string returnUrl)
		{
			Product product = _repository.Products.FirstOrDefault(p => p.ProductID == productID);

			if (product != null)
				_cart.AddItem(product, 1);

			return RedirectToAction("Index", new { returnUrl });
		}

		public RedirectToActionResult RemoveFromCart(int productID, string returnUrl)
		{
			Product product = _repository.Products.SingleOrDefault(p => p.ProductID == productID);

			if (product != null)
				_cart.RemoveItem(product);

			return RedirectToAction("Index", new { returnUrl });
		}
	}
}

SportStore/SportStore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SportStore.Models;


namespace SportStore.Controllers
{
	public class OrderController : Controller
	{
		private IOrderRepository repository;
		private Cart cart;

		public OrderController(IOrderRepository repository, Cart cart)
		{
			this.repository = repository;
			this.cart = cart;
		}

		[Authorize]
		public ViewResult List()
		{
			return View(repository.Orders.Where(o => !o.Shipped));
		}

		[HttpPost]
		[Authorize]
		public IActionResult MarkShipped(int orderId)
		{
			Order order = repository.Orders.FirstOrDefault(o => o.OrderId == orderId);
			if(order != null)
			{
				order.Shipped = true;
				repository.SaveOrder(order);
			}
			return RedirectToAction(nameof(List));
		}

		public ViewResult Checkout()
		{
			return View(new Order());
		}

		[HttpPost]
		public IActionResult Checkout(Order order)
		{
			if(cart.LinesCollection.Count() == 0)
			{
				ModelState.AddModelError("", "Koszyk jest pusty!");
			}

			if(ModelState.IsValid)
			{
				order.Lines = cart.LinesCollection.ToArray();
				repository.SaveOrder(order);
				return RedirectToAction(nameof(Completed));
			}
			else
			{
				return View(order);
			}
		}

		public ViewResult Completed()
		{
			cart.ClearCart();
			return View();
		}
	}
}

SportStore/SportStore/Views/Cart/Index.cshtml
@model CartIndexViewModel

<h2>Twój koszyk</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Ilość</th>
            <th>Produkt</th>
            <th class="text-right">Cena</th>
            <th class="text-right">Wartość</th>
        </tr>
    </thead>
    <tbody>
        @foreach (CartLine p in Model.Cart.LinesCollection)
        {
            <tr>
                <td class="text-center">@p.Quantity</td>
                <td class="text-center">@p.Product.Name</td>
                <td class="text-center">@p.Product.Price</td>
                <td class="text-center">@((p.Product.Price * p.Quantity).ToString("c"))</td>
                <td>
                    <form class="form-delete-product" asp-action="RemoveFromCart" asp-controller="Cart" method="post">
                        <input type="hidden" name="ProductID" value="@p.Product.ProductID" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl">
                        <button type="submit" class="btn btn-sm btn-danger button-product-remove">
                            Usuń
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot class="text-center">
        <tr>
            <td colspan="3" class="text-right">Razem:</td>
            <td class="text-right">@Model.Cart.ComputeTotalValue()</td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">
        Kontynuuj zakupy
    </a>
    <a class="btn btn-success" asp-action="Checkout" asp-controller="Order">
        Złóż zamówienie
    </a>
</div>